sudo: false
language: node_js
env:
  - SERVICES=peters,pub,tankovna,u-sani,meat-market
branches:
  only:
    - master
cache:
  directories:
    - node_modules
node_js:
  - 'stable'
script: npm run test:ci
